### ISSUE TITLE
지원프로그램 정보 에러 수정

### ISSUE THREAD

**Issue by Lib0823** [woojin0906/Provi-disabled_App#12]
지도에서 현재 사용자 위치와 프로그램 위치 폴리라인 찍는거 잘 되요...........
![화면 캡처 2023-05-21 022003](https://github.com/woojin0906/Provi-disabled_App/assets/89591782/95dafadd-2261-43d8-9093-8b8777a433a4)

**Comment by woojin0906** [comment]
확인했습니다
